spring:
    application:
        name: cart-service
    data:
        mongodb:
            uri: mongodb://127.0.0.1:27017/purely_cart_service

server:
    port: 9060

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
